DS1_6/config/routes.rb
Rails.application.routes.draw do
  resources :developers
  resources :projects
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'projects#index'
  # Defines the root path route ("/")
  # root "articles#index"
end

DS1_6/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

DS1_6/app/models/developer.rb
class Developer < ApplicationRecord
  belongs_to :project
end

DS1_6/app/models/project.rb
class Project < ApplicationRecord
end

DS1_6/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

DS1_6/app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  before_action :set_developer, only: %i[ show edit update destroy ]

  # GET /developers or /developers.json
  def index
    @developers = Developer.all
  end

  # GET /developers/1 or /developers/1.json
  def show
  end

  # GET /developers/new
  def new
    @developer = Developer.new
  end

  # GET /developers/1/edit
  def edit
  end

  # POST /developers or /developers.json
  def create
    @developer = Developer.new(developer_params)

    respond_to do |format|
      if @developer.save
        format.html { redirect_to developer_url(@developer), notice: "Developer was successfully created." }
        format.json { render :show, status: :created, location: @developer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @developer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /developers/1 or /developers/1.json
  def update
    respond_to do |format|
      if @developer.update(developer_params)
        format.html { redirect_to developer_url(@developer), notice: "Developer was successfully updated." }
        format.json { render :show, status: :ok, location: @developer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @developer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /developers/1 or /developers/1.json
  def destroy
    @developer.destroy

    respond_to do |format|
      format.html { redirect_to developers_url, notice: "Developer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_developer
      @developer = Developer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def developer_params
      params.require(:developer).permit(:name, :surname, :project_id)
    end
end

DS1_6/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :team, :info)
    end
end

DS1_6/app/helpers/application_helper.rb
module ApplicationHelper
end

DS1_6/app/helpers/developers_helper.rb
module DevelopersHelper
end

DS1_6/app/helpers/projects_helper.rb
module ProjectsHelper
end

DS1_6/app/views/developers/_developer.html.erb
<div id="<%= dom_id developer %>">
  <p>
    <strong>Name:</strong>
    <%= developer.name %>
  </p>

  <p>
    <strong>Surname:</strong>
    <%= developer.surname %>
  </p>

  <p>
    <strong>Project:</strong>
    <%= developer.project_id %>
  </p>

</div>

DS1_6/app/views/developers/_form.html.erb
<%= form_with(model: developer) do |form| %>
  <% if developer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(developer.errors.count, "error") %> prohibited this developer from being saved:</h2>

      <ul>
        <% developer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :surname, style: "display: block" %>
    <%= form.text_field :surname %>
  </div>

  <div>
    <%= form.label :project_id, style: "display: block" %>
    <%= form.text_field :project_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

DS1_6/app/views/developers/edit.html.erb
<h1>Editing developer</h1>

<%= render "form", developer: @developer %>

<br>

<div>
  <%= link_to "Show this developer", @developer %> |
  <%= link_to "Back to developers", developers_path %>
</div>

DS1_6/app/views/developers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Developers</h1>

<div id="developers">
  <% @developers.each do |developer| %>
    <%= render developer %>
    <p>
      <%= link_to "Show this developer", developer %>
    </p>
  <% end %>
</div>

<%= link_to "New developer", new_developer_path %>

DS1_6/app/views/developers/new.html.erb
<h1>New developer</h1>

<%= render "form", developer: @developer %>

<br>

<div>
  <%= link_to "Back to developers", developers_path %>
</div>

DS1_6/app/views/developers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @developer %>

<div>
  <%= link_to "Edit this developer", edit_developer_path(@developer) %> |
  <%= link_to "Back to developers", developers_path %>

  <%= button_to "Destroy this developer", @developer, method: :delete %>
</div>

DS1_6/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DS16</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <%= link_to "Projects", root_path %>
    <%= link_to "Developers", :developers %>
  </body>
</html>

DS1_6/app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :team, style: "display: block" %>
    <%= form.number_field :team %>
  </div>

  <div>
    <%= form.label :info, style: "display: block" %>
    <%= form.text_area :info %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

DS1_6/app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Team:</strong>
    <%= project.team %>
  </p>

  <p>
    <strong>Info:</strong>
    <%= project.info %>
  </p>

</div>

DS1_6/app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

DS1_6/app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<%= link_to "New project", new_project_path %>

DS1_6/app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

DS1_6/app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project) %> |
  <%= link_to "Back to projects", projects_path %>

  <%= button_to "Destroy this project", @project, method: :delete %>
</div>